Dev
Outkarm/javascript-capstone-group-project pull request #26
Opened 2023-01-14 19:50 UTC by Outkarm

add all functions and files to the project

2023-01-14 20:01 UTC, brainskev commented
## Status: Approved ✔️

**Hi @Outkarm,**

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 

![128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c](https://user-images.githubusercontent.com/81444338/150871274-7d1b779c-88e6-420b-a530-b7b905eaa3ac.gif)

You may close this Pull Request and merge the changes
Keep being awesome dev's and good luck with your next milestone!

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally.
✅ Commit messages are meaningful.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-01-14 20:17 UTC, 1GORDON requested changes
##
## Hi @Outkarm & @brainskev ✋

Good job so far!

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Linters are passing ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 20:17 UTC, 1GORDON commented on README.md
> +![](https://img.shields.io/badge/Microverse-blueviolet)
Great job team 🤝

- [ ] As stated in the general requirements, kindly use the correct readme template and customize it accordingly. Here is the link to the correct [readme template](https://github.com/microverseinc/readme-template).

2023-01-14 20:17 UTC, 1GORDON commented on README.md
> +## 📝 License
Great job team 🤝

- [ ] [Optional] Kindly fix the broken MIT license link to make your readme file more professional.

2023-01-14 20:17 UTC, 1GORDON commented on src/modules/commentCounter.js
> +const commentNum = async () => {
Great job team 🤝

- [ ] [Optional] You may kindly make sure the comments counter updates in real-time. In this case, the comments-counter updates when the page reloads.

2023-01-14 20:17 UTC, 1GORDON commented on src/modules/commentCounter.test.js
> +describe('counting test', () => {
Great job team 🤝

- [ ] You may kindly fix the failing test cases. A the moment both test cases are failing.
![test-fail](https://user-images.githubusercontent.com/63917725/212494645-faba910d-d904-43d6-b18f-4927b4b10017.PNG)

2023-01-15 00:36 UTC, andersonlebon requested changes
## Hi @Outkarm && @brainskev 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)

## Suggested changes
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-01-15 00:36 UTC, andersonlebon commented on src/modules/commentCounter.test.js
> +    expect(theCount).toBe(2);
- [ ] Kindly note that you should write unit tests for some of the functionality of your app. I am really sorry but your code above is not testing any of the functionality of the App. and you are still having some failing tests, Kindly solve the as said by the first Reviewer

![image](https://user-images.githubusercontent.com/65068771/212503120-9b9f99b5-478f-4c84-a714-7aeafb57ac76.png)

2023-01-15 00:36 UTC, andersonlebon commented on src/modules/itemCounter.test.js
> +});
- [ ] Kindly note that you should write unit tests for some of the functionality of your app. I am really sorry but your code above is not testing any of the functionality of the App. and you are still having some failing tests, Kindly solve the as said by the first Reviewer

![image](https://user-images.githubusercontent.com/65068771/212503120-9b9f99b5-478f-4c84-a714-7aeafb57ac76.png)

2023-01-16 09:15 UTC, Lameck1 requested changes
Hi @Outkarm, 

This is a manual review.

You have refactored your code as directed in the previous reviews. However, tests are still not running as expected 👇🏼:

![image](https://user-images.githubusercontent.com/45002654/212640523-fa9f3fc9-87d4-4067-a4f5-887332426c0a.png)

This is because of this error 👇🏼:

![image](https://user-images.githubusercontent.com/45002654/212640683-9e18e36a-8bde-4356-8dad-6468ccb46062.png)

There is a module missing in your project dependencies. Tests might be running successfully on your because this missing module might have been installed globally on your computer.

Cheers, and happy coding.

2023-01-16 09:27 UTC, Lameck1 requested changes
This an additional comment.

After installing the missing dependency with 👇🏼:

```bash
npm install --save-dev @babel/preset-typescript
```

The test now can run but all of the still fail as show below:

![image](https://user-images.githubusercontent.com/45002654/212643493-dd37b951-bce7-4ad2-834e-28a8b6589f60.png)

2023-01-16 09:28 UTC, Outkarm commented
@Lameck1  please I have installed babel/preset typescript, please check

2023-01-16 09:30 UTC, Outkarm commented
![Capture](https://user-images.githubusercontent.com/108669691/212644457-28adafec-b938-44c5-8f61-09f04e5c2792.PNG)

2023-01-16 09:32 UTC, Outkarm commented
@Lameck1 please my life depends on this please sir approve

2023-01-16 10:00 UTC, Lameck1 approved these changes
Hi, @Outkarm,

This is a manual review.

Based on the information you've shared, tasks for this project are now considered successfully implemented 💯.

All the best with the next project.

You are free to merge this branch :shipit:
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

2023-01-16 10:02 UTC, merged